SET FOREIGN_KEY_CHECKS = 0; 
ALTER TABLE actor MODIFY COLUMN id BIGINT;
ALTER TABLE director MODIFY COLUMN id BIGINT;
ALTER TABLE directs MODIFY COLUMN director_id BIGINT;
ALTER TABLE plays MODIFY COLUMN actor_id BIGINT;
ALTER TABLE likes_actor MODIFY COLUMN actor_id BIGINT;
ALTER TABLE likes_director MODIFY COLUMN director_id BIGINT;
SET FOREIGN_KEY_CHECKS = 1;